# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "<api_key>"
application_url = "https://wild-focus-outdoors-yr.trycloudflare.com"
embedded = true
name = "remix"
handle = "remix-114"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
dev_store_url = "shopifast.myshopify.com"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/update" ]
  uri = "/webhooks/app/subscriptions_update"

  [[webhooks.subscriptions]]
  topics = [ "app_purchases_one_time/update" ]
  uri = "/webhooks/app/one_time_purchase_updated"

  [[webhooks.subscriptions]]
  topics = [ "app_subscriptions/approaching_capped_amount" ]
  uri = "/webhooks/app/approaching_capped_amount"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://wild-focus-outdoors-yr.trycloudflare.com/auth/callback",
  "https://wild-focus-outdoors-yr.trycloudflare.com/auth/shopify/callback",
  "https://wild-focus-outdoors-yr.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
